# ************************************************************
# Sequel Pro SQL dump
# Version 4541
#
# http://www.sequelpro.com/
# https://github.com/sequelpro/sequelpro
#
# Host: 127.0.0.1 (MySQL 5.7.20)
# Database: mdb
# Generation Time: 2017-11-02 11:58:47 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table films
# ------------------------------------------------------------

DROP TABLE IF EXISTS `films`;

CREATE TABLE `films` (
  `id` int(11) unsigned NOT NULL DEFAULT '0',
  `versionId` int(11) unsigned NOT NULL DEFAULT '1',
  `changerId` int(11) unsigned NOT NULL,
  `title` varchar(100) NOT NULL,
  `year` year(4) DEFAULT NULL,
  `genre` set('Action','Adventure','Animation','Comedy','Crime','Documentary','Drama','Horror','Musical','Romantic','Science Fiction','Thriller','War','Western') DEFAULT NULL,
  `plot` varchar(3000) DEFAULT NULL,
  `imagePath` varchar(500) DEFAULT 'default.png',
  `youtubeUrl` varchar(200) DEFAULT NULL,
  `timeCreated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`versionId`),
  KEY `FK_films_users` (`changerId`),
  CONSTRAINT `FK_films_users` FOREIGN KEY (`changerId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `films` WRITE;
/*!40000 ALTER TABLE `films` DISABLE KEYS */;

INSERT INTO `films` (`id`, `versionId`, `changerId`, `title`, `year`, `genre`, `plot`, `imagePath`, `youtubeUrl`, `timeCreated`)
VALUES
	(1,1,1,'It','2017','Horror','Suddenly, the small town of Derry, in the US state of Maine, is freaking out of terror when several children mysteriously begin to disappear. Some children face their biggest fears when they end up in the evil clown Pennywise Society, whose story as a killer extends far, far back in time. Bill Skarsgård plays the lead in the new horror movie It builds on Stephen Kings well-known novel with the same name.','default.png','https://www.youtube.com/watch?v=xKJmEC5ieOk','2017-11-01 22:40:11'),
	(1,2,6,'Not It','2017','Horror','Suddenly, the small town of Derry, in the US state of Maine, is freaking out of terror when several children mysteriously begin to disappear. Some children face their biggest fears when they end up in the evil clown Pennywise Society, whose story as a killer extends far, far back in time. Bill Skarsgård plays the lead in the new horror movie It builds on Stephen Kings well-known novel with the same name.','default.png','https://www.youtube.com/watch?v=xKJmEC5ieOk','2017-11-02 12:40:35'),
	(2,1,1,'Harry Potter and the Chamber of Secrets','2002','Adventure','The summer break is finally over! Harry Potter has longed back to his second year at Hogwarts School for Witchcraft and Witchcraft. But how will he stand out with the new, meticulous professor Lockman? What hides Hagrids past? And who\'s really unhappy myrtle? The real problems begin when someone, or something, glorifies one Hogwarteleven after another. Is it Harry\'s greatest enemy, Draco Malfoy, behind? Or is it that everyone at Hogwarts suspects - Harry Potter himself?','harry_potter_and_the_chamber_of_secrets.jpg','https://www.youtube.com/watch?v=1bq0qff4iF8','2017-11-02 12:38:40'),
	(2,2,6,'Furry Potter and the Chamber of Secrets','2002','Adventure','The summer break is finally over! Harry Potter has longed back to his second year at Hogwarts School for Witchcraft and Witchcraft. But how will he stand out with the new, meticulous professor Lockman? What hides Hagrids past? And who\'s really unhappy myrtle? The real problems begin when someone, or something, glorifies one Hogwarteleven after another. Is it Harry\'s greatest enemy, Draco Malfoy, behind? Or is it that everyone at Hogwarts suspects - Harry Potter himself?','harry_potter_and_the_chamber_of_secrets.jpg','https://www.youtube.com/watch?v=1bq0qff4iF8','2017-11-02 12:40:30'),
	(3,1,1,'The Rock','1996','Action','A mStanley Goodspeed, who lives in Washington D.C., is a biochemist who works for the FBI. Soon after his fiancée Carla Pestalozzi announces that she is pregnant, Stanley gets a call from FBI director James Womack. Womack tells Stanley that San Francisco´s Alcatraz Island has been taken hostage, along with 81 tourists, by marine General Francis Xavier Hummel who, for years, has been protesting the government´s refusal to pay benefits to families of war veterans who died during covert military operations. The death of his wife Barbara Hummel on March 9, 1995 drove General Hummel over the edge, and now he´s holding hostages in order to get his point across. Stanley is needed because General Hummel has stolen some VX gas warheads and has announced that he will launch them onto San Francisco unless his demands are met. Stanley knows how to disarm the bombs, but Stanley needs someone who knows Alcatraz well enough to get him inside. That man is former British intelligence agent John Patrick.','the_rock.jpg','https://www.youtube.com/watch?v=6DWu_dT0Phc','2017-11-02 12:22:23'),
	(4,1,1,'Con Air','1997','Action','Cameron Poe, a highly decorated United States Army Ranger, came home to Alabama to his wife, Tricia, only to run into a few drunken regulars where Tricia works. Cameron unknowingly kills one of the drunks and is sent to a federal penitentiary for involuntary manslaughter for seven years. Cameron becomes eligible for parole and can now go home to his wife and daughter. Unfortunately, Cameron has to share a prison airplane with some of the country´s most dangerous criminals, who took control of the plane and are now planning to escape the country. Cameron has to find a way to stop them while playing along. Meanwhile, United States Marshal Vincent Larkin is trying to help Cameron get free and stop the criminals, including Cyrus \"The Virus\" Grissom.','con_air.jpg','https://www.youtube.com/watch?v=EmTO6Z4_EvE','2017-11-02 12:22:00'),
	(5,1,1,'Yes Man','2008','Comedy','Carl Allen is at a standstill. No future... Until the day he enrolls into a personal development program based on a very simple idea: say yes to everything! Carl discovers with amazement the magical power of \"Yes\", and sees his professional and romantic life turned upside down overnight: an unexpected promotion and a new girlfriend. But he´ll soon discover that better can be good´s enemy, and that all opportunities shouldn´t be taken.','yes_man.jpg','https://www.youtube.com/watch?v=yEYt-aP7klU','2017-11-02 12:17:30'),
	(6,1,1,'Blade Runner 2049','2017','Thriller','Thirty years after the events of the first film, a new blade runner, LAPD Officer K (Ryan Gosling), unearths a long-buried secret that has the potential to plunge what´s left of society into chaos. K´s discovery leads him on a quest to find Rick Deckard (Harrison Ford), a former LAPD blade runner who has been missing for 30 years.','blade_runner.jpg','https://www.youtube.com/watch?v=6T2b0mp2hco','2017-11-02 12:15:17'),
	(7,1,1,'Toy Story','1995','Animation','A little boy named Andy loves to be in his room, playing with his toys, especially his doll named \"Woody\". But, what do the toys do when Andy is not with them, they come to life. Woody believes that he has life (as a toy) good. However, he must worry about Andy´s family moving, and what Woody does not know is about Andy´s birthday party. Woody does not realize that Andy´s mother gave him an action figure known as Buzz Lightyear, who does not believe that he is a toy, and quickly becomes Andy´s new favorite toy. Woody, who is now consumed with jealousy, tries to get rid of Buzz. Then, both Woody and Buzz are now lost. They must find a way to get back to Andy before he moves without them, but they will have to pass through a ruthless toy killer, Sid Phillips.','toy_story.jpg','https://www.youtube.com/watch?v=4KPTXpQehio','2017-11-02 12:14:01'),
	(8,1,1,'Chappie','2015','Action','In Johannesburg, the police department reduced the high rating of criminality using robots from the Tetravaal Company, designed by the engineer Deon Wilson. The former military Vincent Moore is envious of Deon, since he has developed another project called Moose, but neither Tetravaal nor the police department is interested. Deon has just developed an Artificial Intelligence but the Tetravaal´s CEO Michelle Bradley asks him to abort the project. Deon decides to bring the damaged Robot 22 that was sent to be crushed to test his A.I. However he is kidnapped by the criminals Ninja, Yo-Landi and Amerika that want him to stop the robot cops. When they see the damaged robot in the van, they force Deon to program it to heist banks with them and they call it Chappie. However, Chappie acts like a child and need to be trained to learn and grow. Meanwhile Vincent follows Deon and plots an evil scheme to activate his robot.','chappie.jpg','https://www.youtube.com/watch?v=l6bmTNadhJE','2017-11-02 12:07:08'),
	(9,1,1,'Her','2013','Drama','Theodore is a lonely man in the final stages of his divorce. When he´s not working as a letter writer, his down time is spent playing video games and occasionally hanging out with friends. He decides to purchase the new OS1, which is advertised as the world´s first artificially intelligent operating system, \"It´s not just an operating system, it´s a consciousness,\" the ad states. Theodore quickly finds himself drawn in with Samantha, the voice behind his OS1. As they start spending time together they grow closer and closer and eventually find themselves in love. Having fallen in love with his OS, Theodore finds himself dealing with feelings of both great joy and doubt. As an OS, Samantha has powerful intelligence that she uses to help Theodore in ways others hadn´t, but how does she help him deal with his inner conflict of being in love with an OS?','her.jpg','https://www.youtube.com/watch?v=ne6p6MfLBxc','2017-11-02 12:29:31'),
	(10,1,1,'Dredd','2012','Action','The future America is an irradiated waste land. On its East Coast, running from Boston to Washington DC, lies Mega City One - a vast, violent metropolis where criminals rule the chaotic streets. The only force of order lies with the urban cops called \"Judges\" who possess the combined powers of judge, jury and instant executioner. Known and feared throughout the city, Dredd is the ultimate Judge, challenged with ridding the city of its latest scourge - a dangerous drug epidemic that has users of \"Slo-Mo\" experiencing reality at a fraction of its normal speed. During a routine day on the job, Dredd is assigned to train and evaluate Cassandra Anderson, a rookie with powerful psychic abilities thanks to a genetic mutation. A heinous crime calls them to a neighborhood where fellow Judges rarely dare to venture - a 200 storey vertical slum controlled by prostitute turned drug lord Ma-Ma and her ruthless clan. When they capture one of the clan´s inner circle, Ma-Ma overtakes the compound´s ...','dredd.jpg','https://www.youtube.com/watch?v=qVIba2N6MTA','2017-11-02 12:43:08'),
	(11,1,1,'Iron Man','2008','Action','Tony Stark. Genius, billionaire, playboy, philanthropist. Son of legendary inventor and weapons contractor Howard Stark. When Tony Stark is assigned to give a weapons presentation to an Iraqi unit led by Lt. Col. James Rhodes, he´s given a ride on enemy lines. That ride ends badly when Stark´s Humvee that he´s riding in is attacked by enemy combatants. He survives - barely - with a chest full of shrapnel and a car battery attached to his heart. In order to survive he comes up with a way to miniaturize the battery and figures out that the battery can power something else. Thus Iron Man is born. He uses the primitive device to escape from the cave in Iraq. Once back home, he then begins work on perfecting the Iron Man suit. But the man who was put in charge of Stark Industries has plans of his own to take over Tony´s technology for other matters.','iron_man.jpg','https://www.youtube.com/watch?v=8hYlB38asDY','2017-11-02 12:44:48'),
	(12,1,1,'Man of Steel','2013','Action','A young boy learns that he has extraordinary powers and is not of this Earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.','man_of_steel.jpg','https://www.youtube.com/watch?v=T6DJcgm3wNY','2017-11-02 12:45:56'),
	(13,1,1,'The Lord of the Rings: The Fellowship of the Ring','2001','Action','An ancient Ring thought lost for centuries has been found, and through a strange twist in fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it! However he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir and his three Hobbit friends Merry, Pippin and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign!','the_lord_of_the_rings_the_fellowship_of_the_ring.jpg','https://www.youtube.com/watch?v=Pki6jbSbXIY','2017-11-02 12:47:55'),
	(14,1,1,'The Lord of the Rings: The Two Towers','2002','Action','The continuing quest of Frodo and the Fellowship to destroy the One Ring. Frodo and Sam discover they are being followed by the mysterious Gollum. Aragorn, the Elf archer Legolas and Gimli the Dwarf encounter the besieged Rohan kingdom, whose once great King Theoden has fallen under Saruman´s deadly spell.','the_lord_of_the_rings_the_two_towers.jpg','https://www.youtube.com/watch?v=2dlRvAjU_RI','2017-11-02 12:50:52'),
	(15,1,1,'The Lord of the Rings: The Return of the King','2003','Action','The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Hobbits: Frodo and Sam reach Mordor in their quest to destroy the \"one ring\", while Aragorn leads the forces of good against Sauron´s evil army at the stone city of Minas Tirith.','the_lord_of_the_rings_the_return_of_the_king.jpg','https://www.youtube.com/watch?v=WIrRJ8bCZYQ','2017-11-02 12:51:49'),
	(16,1,1,'Fight Club','1999','Drama','A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler´s fight club, he must accept the awful truth that Tyler may not be who he says he is.','fight_club.jpg','https://www.youtube.com/watch?v=_XgQA9Ab0Gw','2017-11-02 12:19:37'),
	(17,1,1,'The Shawshank Redemption','1994','Crime','Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man´s unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.','the_shawshank_redemption.jpg','https://www.youtube.com/watch?v=6hB3S9bIaco','2017-11-02 12:54:27'),
	(18,1,1,'Leon','1994','Crime','After her father, mother, older sister and little brother are killed by her father´s employers, the 12-year-old daughter of an abject drug dealer is forced to take refuge in the apartment of a professional hitman who at her request teaches her the methods of his job so she can take her revenge on the corrupt DEA agent who ruined her life by killing her beloved brother.','leon.jpg','https://www.youtube.com/watch?v=DcsirofJrlM','2017-11-02 12:55:13'),
	(19,1,1,'Interstellar','2014','Adventure','Earth´s future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind´s survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.','interstellar.jpg','https://www.youtube.com/watch?v=zSWdZVtXT7E','2017-11-02 12:56:59'),
	(20,1,1,'Gladiator','2000','Action','Maximus is a powerful Roman general, loved by the people and the aging Emperor, Marcus Aurelius. Before his death, the Emperor chooses Maximus to be his heir over his own son, Commodus, and a power struggle leaves Maximus and his family condemned to death. The powerful general is unable to save his family, and his loss of will allows him to get captured and put into the Gladiator games until he dies. The only desire that fuels him now is the chance to rise to the top so that he will be able to look into the eyes of the man who will feel his revenge.','gladiator.jpg','https://www.youtube.com/watch?v=Q-b7B8tOAQU','2017-11-02 12:56:50'),
	(21,1,1,'Forest Gump','1994','Comedy','Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His \"mama\" teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.','forrest_gump.jpg','https://www.youtube.com/watch?v=uPIEn0M8su0','2017-11-02 12:58:30'),
	(22,1,1,'Notorious!','1946','Thriller','','default.png','','2017-11-01 22:34:08'),
	(23,1,1,'Vertigo','1958','Thriller','','vertigo.jpg','','2017-11-01 22:35:14'),
	(24,1,1,'The Big Lebowski','1998','Comedy','','default.png','','2017-11-01 22:40:31'),
	(25,1,1,'The Day of the Locust','1975','Drama','','default.png','','2017-11-01 22:40:32'),
	(26,1,1,'Midnight Cowboy','1969','Drama','','default.png','','2017-11-01 22:40:33'),
	(27,1,1,'The Wrestler','2008','Drama','','default.png','','2017-11-01 22:40:34'),
	(28,1,1,'What Ever Happened to Baby Jane?','1962','Drama','','default.png','','2017-11-01 22:40:35'),
	(29,1,1,'Seance on a Wet Afternoon','1964','Crime','','default.png','','2017-11-01 22:40:36'),
	(30,1,1,'Paper Moon','1973','Drama','','default.png','','2017-11-01 22:40:37'),
	(31,1,4,'North by Northwest','1959','Thriller','','default.png','','2017-11-01 22:40:38');

/*!40000 ALTER TABLE `films` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
